apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deschedbench-descheduler
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: deschedbench-descheduler
  endpoints:
    - port: metrics
      interval: 5s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
